<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MAK_Modbus_Simulator</AssemblyName>
    <RootNamespace>SimulatorWpfApp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\simulator\MAK_Modbus.Simulator\MAK_Modbus.Simulator.csproj" />
    <ProjectReference Include="..\..\src\MAK_Modbus\MAK_Modbus.csproj" />
  </ItemGroup>
</Project>
