<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MAK_Modbus.Simulator</AssemblyName>
    <RootNamespace>MAK_Modbus.Simulator</RootNamespace>
  </PropertyGroup>
</Project>
