<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BmsTestSystem</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/MAK_Modbus/MAK_Modbus.csproj" />
  </ItemGroup>

  <!-- 빌드 출력 디렉터리에 JSON 설정 파일 복사 -->
  <ItemGroup>
    <None Update="config/sequence.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
